// @generated by `cargo run --quiet -p web --bin emit_abi` -- do not edit.

export const FRAME_LAYOUT_VERSION = 7;
export const HEADER_LEN = 15;
export const UNIT_STRIDE = 33;
export const SHOT_STRIDE = 4;
export const EVENT_STRIDE = 8;
export const FURNITURE_STRIDE = 4;

export const MAX_UNITS = 64;
export const MAX_SHOTS = 32;
export const MAX_EVENTS = 128;
export const FRAME_MAX = 3279;
export const MAP_MAX = 6144;
export const FURNITURE_MAX = 512;

export const FRAME_OFFSET = 0;
export const MAP_OFFSET = 13116;
export const VIS_OFFSET = 19260;
export const FURNITURE_OFFSET = 25404;
export const SNAPSHOT_BUFFER_BYTES = 27452;

export const HEADER_ARENA_X = 0;
export const HEADER_ARENA_Y = 1;
export const HEADER_ORDER_KIND = 2;
export const HEADER_ORDER_X = 3;
export const HEADER_ORDER_Y = 4;
export const HEADER_LAST_DECISION_TICK = 5;
export const HEADER_UNIT_COUNT = 6;
export const HEADER_SHOT_COUNT = 7;
export const HEADER_EVENT_COUNT = 8;
export const HEADER_MONSTERS_LEFT = 9;
export const HEADER_PORTAL_X = 10;
export const HEADER_PORTAL_Y = 11;
export const HEADER_PORTAL_STATE = 12;
export const HEADER_DEPTH = 13;
export const HEADER_EVENTS_DROPPED = 14;

export const RAW_ANGLE_TURN = 65536;
export const MAP_TILE_MILLI = 1000;
export const MAP_OPEN = 0;
export const MAP_SOLID = 1;
export const MAP_UNKNOWN = 255;

export const UNIT_X = 0;
export const UNIT_Y = 1;
export const UNIT_FACING_RAW = 2;
export const UNIT_RADIUS = 3;
export const UNIT_HP = 4;
export const UNIT_MAX_HP = 5;
export const UNIT_FACTION = 6;
export const UNIT_KIND = 7;
export const UNIT_INTENT = 8;
export const UNIT_ENTITY_INDEX = 9;
export const UNIT_ENTITY_GENERATION = 10;
export const UNIT_LIMB_ANGLE_RAW = 11;
export const UNIT_LIMB_REACH = 12;
export const UNIT_LIMB_SPIN = 13;
export const UNIT_ACTION_LENGTH = 14;
export const UNIT_ACTION_ARC_RAW = 15;
export const UNIT_HIT_FLASH = 16;
export const UNIT_BLOCK_FLASH = 17;
export const UNIT_PARRY_FLASH = 18;
export const UNIT_LIMB_SWING = 19;
export const UNIT_LIMB_SWING_LEFT = 20;
export const UNIT_LIMB_LINE_RAW = 21;
export const UNIT_ACTION_KIND = 22;
export const UNIT_ACTION_ROLE = 23;
export const UNIT_SLOT = 24;
export const UNIT_SLOT0_ACTION = 25;
export const UNIT_SLOT1_ACTION = 26;
export const UNIT_SIGHT_RANGE = 27;
export const UNIT_VISIBLE = 28;
export const UNIT_VX = 29;
export const UNIT_VY = 30;
export const UNIT_STRIDE_PHASE = 31;
export const UNIT_SWING_SPAN = 32;

export const SHOT_X = 0;
export const SHOT_Y = 1;
export const SHOT_HEADING_RAW = 2;
export const SHOT_FACTION = 3;

export const EVENT_KIND = 0;
export const EVENT_X = 1;
export const EVENT_Y = 2;
export const EVENT_AMOUNT = 3;
export const EVENT_ACTOR_INDEX = 4;
export const EVENT_OTHER_INDEX = 5;
export const EVENT_AUX0 = 6;
export const EVENT_AUX1 = 7;
export const EVENT_DAMAGE = 0;
export const EVENT_BLOCK = 1;
export const EVENT_PARRY = 2;
export const EVENT_DECLARE = 3;
export const EVENT_DEATH = 4;
export const EVENT_LOOSE = 5;
export const EVENT_PHASE = 6;
export const EVENT_STEP = 7;
export const EVENT_SHOVE = 8;
export const EVENT_PORTAL = 9;
export const EVENT_DESCEND = 10;
export const EVENT_KINDS = 11;

export const FURNITURE_KIND = 0;
export const FURNITURE_TX = 1;
export const FURNITURE_TY = 2;
export const FURNITURE_STATE = 3;
export const FURNITURE_DOOR = 1;
export const FURNITURE_TORCH = 2;
export const FURNITURE_DOOR_SHUT = 0;
export const FURNITURE_DOOR_OPEN = 1;
export const TORCH_FACE_POS_X = 0;
export const TORCH_FACE_POS_Y = 1;

export const FOCUS_NONE = 4294967295;
export const FOCUS_IDENTITY_EXPORTS = [
  "focus_entity_index",
  "focus_entity_generation",
] as const;
