// @generated by `cargo run --quiet -p web --bin emit_abi` -- do not edit.

export const FRAME_LAYOUT_VERSION = 7;
export const HEADER_LEN = 15;
export const UNIT_STRIDE = 33;
export const SHOT_STRIDE = 4;
export const EVENT_STRIDE = 8;
export const FURNITURE_STRIDE = 4;

export const MAX_UNITS = 64;
export const MAX_SHOTS = 32;
export const MAX_EVENTS = 128;
export const FRAME_MAX = 3279;
export const MAP_MAX = 6144;
export const FURNITURE_MAX = 512;

export const FRAME_OFFSET = 0;
export const MAP_OFFSET = 13116;
export const VIS_OFFSET = 19260;
export const FURNITURE_OFFSET = 25404;
export const SNAPSHOT_BUFFER_BYTES = 27452;

export const HEADER_ARENA_X = 0;
export const HEADER_ARENA_Y = 1;
export const HEADER_ORDER_KIND = 2;
export const HEADER_ORDER_X = 3;
export const HEADER_ORDER_Y = 4;
export const HEADER_LAST_DECISION_TICK = 5;
export const HEADER_UNIT_COUNT = 6;
export const HEADER_SHOT_COUNT = 7;
export const HEADER_EVENT_COUNT = 8;
export const HEADER_MONSTERS_LEFT = 9;
export const HEADER_PORTAL_X = 10;
export const HEADER_PORTAL_Y = 11;
export const HEADER_PORTAL_STATE = 12;
export const HEADER_DEPTH = 13;
export const HEADER_EVENTS_DROPPED = 14;

export const UNIT_ENTITY_INDEX = 9;
export const UNIT_ENTITY_GENERATION = 10;
export const UNIT_VISIBLE = 28;

export const FOCUS_NONE = 4294967295;
export const FOCUS_IDENTITY_EXPORTS = [
  "focus_entity_index",
  "focus_entity_generation",
] as const;

export const MAP_UNKNOWN = 255;
