// Builds the authored warrior, and pins the one that is committed.
//
//     node scripts/run-blender.mjs            rebuild the glb (needs Blender)
//     node scripts/run-blender.mjs --verify   check the committed one (needs nothing)
//
// or, through npm, `npm run asset:build` and `npm run asset:verify`. Note that
// `npm run asset:build --verify` is *not* the second of those: npm eats a bare
// flag as its own config and the script never sees it, so the two are separate
// entries in `package.json` rather than one entry and a flag nobody can pass.
//
// The built file is committed. That is deliberate and it is the same argument
// `fetch-polyhaven.mjs` makes about the environment map: this work is synced
// across two machines, Blender is a 1 GB dependency, and `npm run dev` must
// come up on a fresh clone with nothing installed but `npm ci`. What committing
// a binary costs is that it can drift from the script that made it, and the two
// checks below are what refuse that drift -- a dimensional one that answers
// whether the asset fits the rig, and a digest that answers whether this working
// copy holds the file the repository does. Read `PIN` for why it can only answer
// the second question.

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { boneFrames, costumePieces } from "../src/figure.ts";
import { CONFIG } from "../src/config.ts";
import { checkWarrior, measurements } from "./check-warrior.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

const GLB = "public/assets/warrior.glb";
const DIMENSIONS = "asset-src/dimensions.json";

/**
 * The digest of the committed `warrior.glb`.
 *
 * **It pins the committed bytes, and it cannot pin the build.** Blender's glTF
 * exporter is not byte-reproducible: two consecutive builds from identical
 * input differ in about 14 000 of 61 662 words of the binary chunk -- almost
 * all of them triangle index order, with a largest float difference of 5.6e-5
 * in a normal -- and `PYTHONHASHSEED=0` does not settle it, so the cause is
 * inside Blender's mesh evaluation rather than in dictionary iteration. Two
 * builds are therefore the same warrior and never the same file.
 *
 * That is exactly why the dimensional check beside this is the real gate and
 * this is not. What the digest is still worth: it catches a working copy that
 * is not what the repository holds, which is the failure this directory is
 * actually exposed to, because the work is synced across two machines and only
 * one of them need have run Blender.
 *
 * Re-record it in the same commit that rebuilds the asset, and only then.
 */
const PIN = "b7d4dab666a4bd4ac8147286a480540b91adde1040bb2d0b9ffc7ee5a11d3338";

/**
 * Everything the Blender script is allowed to know about this rig.
 *
 * The authoring script cannot read TypeScript, and a set of dimensions typed
 * into it by hand is a set of dimensions that is right on the day it is typed.
 * So the numbers go through this file instead: `config.ts` for the body,
 * `figure.ts` for the list of pieces and which bone each one rides on, and a
 * JSON in between that is rewritten immediately before every build.
 *
 * It stays in step three ways, and needs all three. It is **regenerated** on
 * every build, so an asset built after a retuned limb is built to the new limb.
 * It is **committed**, so the numbers the committed `.glb` was cut to are on
 * the record next to it. And `--verify` **recomputes it and compares**, so a
 * `config.ts` edit that moves a bone without a rebuild is a failing check
 * rather than a warrior that no longer fits.
 */
function dimensions() {
  const numbers = (block) =>
    Object.fromEntries(Object.entries(block).filter(([, value]) => typeof value === "number"));

  return {
    schema: 1,
    source: "generated by scripts/run-blender.mjs from src/config.ts and src/figure.ts",
    fighter: numbers(CONFIG.fighter),
    arm: numbers(CONFIG.arm),
    body: numbers(CONFIG.body),
    bones: boneFrames(),
    pieces: costumePieces().map((piece) => ({
      name: piece.name,
      bone: piece.bone,
      material: piece.material,
      at: piece.at,
    })),
  };
}

const asText = (value) => `${JSON.stringify(value, null, 2)}\n`;

const digest = (buffer) => createHash("sha256").update(buffer).digest("hex");

const BLENDER = [
  process.env.BLENDER_PATH,
  "blender",
  resolve(ROOT, "../.tools/blender-4.5.12/blender-4.5.12-windows-x64/blender.exe"),
].filter(Boolean);

function runBlender(args) {
  for (const executable of BLENDER) {
    if ((executable.includes("/") || executable.includes("\\")) && !existsSync(executable)) continue;
    const result = spawnSync(executable, args, { cwd: ROOT, encoding: "utf8", stdio: "inherit" });
    if (result.error?.code === "ENOENT") continue;
    if (result.error) throw result.error;
    return result.status ?? 1;
  }
  throw new Error("Blender was not found. Set BLENDER_PATH or install Blender on PATH.");
}

async function report(expected) {
  const buffer = await readFile(resolve(ROOT, GLB)).catch(() => null);
  if (!buffer) {
    console.error(`missing ${GLB} -- run: npm run asset:build`);
    return false;
  }
  const result = checkWarrior(buffer, expected);
  for (const row of measurements(buffer, expected)) console.log(`  ${row}`);
  console.log("");
  for (const note of result.notes) console.log(`  ${note}`);
  for (const failure of result.failures) console.error(`FAIL ${failure}`);

  const actual = digest(buffer);
  if (actual !== PIN) {
    console.log(
      `\nNOTE: ${GLB} digest is ${actual}\n` +
        `      the pin in scripts/run-blender.mjs says ${PIN}\n` +
        "      Every rebuild says this -- see PIN for why Blender cannot repeat\n" +
        "      itself byte for byte. If you mean to commit this build, paste the\n" +
        "      digest above into PIN in the same commit. If you do not, discard it:\n" +
        "      a rebuilt-but-unpinned asset is a file nobody else can reproduce.",
    );
  }
  return result.ok;
}

/**
 * What actually differs between the committed dimensions and today's.
 *
 * The check used to report "a bone has moved" whenever the two texts differed,
 * which is what it is *for* -- but the file carries every numeric field of
 * `CONFIG.fighter`, `CONFIG.arm` and `CONFIG.body`, and most of those are not
 * dimensions at all. Adding `body.deadJointStrength`, a tuning number no vertex
 * depends on, produced a confident report that a bone had moved. Naming the keys
 * costs a dozen lines and turns "something is wrong somewhere" into an answer.
 */
function whatChanged(committed, expected) {
  let before;
  try {
    before = JSON.parse(committed);
  } catch {
    return ["  the committed file is not readable JSON"];
  }
  const notes = [];
  const walk = (a, b, path) => {
    const keys = new Set([...Object.keys(a ?? {}), ...Object.keys(b ?? {})]);
    for (const key of keys) {
      const here = path ? `${path}.${key}` : key;
      const one = a?.[key];
      const two = b?.[key];
      if (one && two && typeof one === "object" && !Array.isArray(one)) {
        walk(one, two, here);
      } else if (JSON.stringify(one) !== JSON.stringify(two)) {
        notes.push(`  ${here}: ${JSON.stringify(one)} -> ${JSON.stringify(two)}`);
      }
    }
  };
  walk(before, expected, "");
  return notes.length ? notes : ["  the two differ only in formatting"];
}

async function verify() {
  const expected = dimensions();
  const committed = await readFile(resolve(ROOT, DIMENSIONS), "utf8").catch(() => null);
  if (committed !== asText(expected)) {
    console.error(
      `${DIMENSIONS} is not what src/config.ts and src/figure.ts say today:\n` +
        `${whatChanged(committed ?? "", expected).join("\n")}\n` +
        "  If a bone moved, the asset must be rebuilt: npm run asset:build\n" +
        "  If nothing dimensional moved, the file only needs rewriting:" +
        " npm run asset:dimensions",
    );
    process.exit(1);
  }
  console.log(`${DIMENSIONS} matches config.ts.`);

  const buffer = await readFile(resolve(ROOT, GLB)).catch(() => null);
  if (!buffer) {
    console.error(`missing ${GLB} -- run: npm run asset:build`);
    process.exit(1);
  }
  const actual = digest(buffer);
  if (actual !== PIN) {
    console.error(`${GLB} digest ${actual}\n  expected ${PIN}`);
    process.exit(1);
  }
  console.log(`${GLB} matches its pin.`);

  const ok = await report(expected);
  console.log(ok ? "warrior.glb fits the rig." : "warrior.glb does not fit the rig.");
  process.exit(ok ? 0 : 1);
}

async function build() {
  const expected = dimensions();
  mkdirSync(resolve(ROOT, "public/assets"), { recursive: true });
  mkdirSync(resolve(ROOT, "asset-src"), { recursive: true });
  await writeFile(resolve(ROOT, DIMENSIONS), asText(expected));
  console.log(`wrote ${DIMENSIONS} from config.ts`);

  const status = runBlender([
    "--background",
    "--factory-startup",
    "--python",
    resolve(ROOT, "asset-src/build_warrior.py"),
    "--",
    "--dimensions",
    resolve(ROOT, DIMENSIONS),
    "--output",
    resolve(ROOT, GLB),
  ]);
  if (status !== 0) process.exit(status);

  const ok = await report(expected);
  console.log(ok ? "warrior.glb fits the rig." : "warrior.glb does not fit the rig.");
  process.exit(ok ? 0 : 1);
}

/**
 * Rewrite the dimensions file, and nothing else.
 *
 * For the case the message in `verify` names: a number in one of the three
 * blocks changed, no bone moved, and the committed `.glb` is still exactly
 * right. Rebuilding for that would need Blender, would produce different bytes
 * -- the exporter is not reproducible -- and would need a fresh digest pin
 * recorded, all to change a line of JSON that no vertex depends on.
 *
 * Deliberately not something `--verify` does for itself. A check that silently
 * repaired what it was checking would never report a moved bone again.
 */
async function rewrite() {
  await writeFile(resolve(ROOT, DIMENSIONS), asText(dimensions()));
  console.log(`wrote ${DIMENSIONS} from config.ts -- the .glb was NOT rebuilt.`);
  console.log("  Only right when nothing dimensional moved. Read the diff.");
}

const main = process.argv.includes("--verify")
  ? verify
  : process.argv.includes("--dimensions")
    ? rewrite
    : build;
main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
