"""Build or verify the deterministic representative authored assets.

Invoke only through the pinned Blender binary:
  blender --background --factory-startup --python tools/art/build_slice.py -- --verify
  blender --background --factory-startup --python tools/art/build_slice.py -- --target combatants --verify
  blender --background --factory-startup --python tools/art/build_slice.py -- --write
"""

import argparse
import hashlib
import json
import locale
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

import bpy

sys.dont_write_bytecode = True

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent.parent
MANIFEST_PATH = SCRIPT_DIR / "manifest.json"
OUTPUT_DIR = ROOT / "web" / "assets3d"
GENERATED_TS = ROOT / "client" / "src" / "render" / "room-asset.generated.ts"

sys.path.insert(0, str(SCRIPT_DIR))
from export import canonical_bytes, export_glb, semantic_sidecar, sha256_bytes, write_sidecar
from materials import build_materials
from room import build_room


def read_manifest():
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def generator_input_hash(manifest):
    value = dict(manifest)
    value.pop("outputs", None)
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def verify_blender(manifest):
    actual_version = ".".join(str(value) for value in bpy.app.version)
    if actual_version != manifest["toolchain"]["blender"]:
        raise RuntimeError(f"Blender is {actual_version}; expected {manifest['toolchain']['blender']}")
    # `sys.executable` is Blender's bundled Python on Windows. `binary_path` is
    # the executable whose reviewed digest check_toolchain.js records.
    blender_binary = Path(bpy.app.binary_path).resolve()
    digest = hashlib.sha256(blender_binary.read_bytes()).hexdigest()
    if digest != manifest["toolchain"]["blenderBinarySha256"]:
        raise RuntimeError(f"Blender binary SHA-256 is {digest}; expected {manifest['toolchain']['blenderBinarySha256']}")


def clear_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    locale.setlocale(locale.LC_ALL, "C")
    bpy.context.scene.unit_settings.system = "METRIC"
    bpy.context.scene.unit_settings.length_unit = "METERS"
    bpy.context.scene.unit_settings.scale_length = 1


def find_node():
    toolchain = json.loads((ROOT / "tools" / "toolchain.json").read_text(encoding="utf-8"))
    relative = toolchain["downloads"]["nodeWindowsX64Zip"]["localExecutablePath"]
    path = ROOT / Path(relative)
    if not path.is_file():
        raise RuntimeError(f"pinned Node executable is missing: {path}")
    return path


def run_validator(glb, sidecar, report):
    command = [str(find_node()), str(ROOT / "tools" / "validate_assets.js"), str(glb),
               "--sidecar", str(sidecar), "--manifest", str(MANIFEST_PATH),
               "--report", str(report), "--skip-expected-hashes"]
    completed = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        raise RuntimeError(f"asset validation failed:\n{completed.stdout}{completed.stderr}")


def build_once(directory, manifest, source_hash):
    clear_scene()
    materials = build_materials(manifest["materials"], manifest["textures"],
                                manifest["textureProcessing"], ROOT)
    meshes, socket = build_room(manifest, materials)
    bpy.ops.object.select_all(action="DESELECT")
    for obj in [*meshes.values(), socket]:
        obj.select_set(True)
    glb = directory / "room_slice.glb"
    sidecar = directory / "room_slice.json"
    report = directory / "room_slice.validator.json"
    export_glb(glb, manifest["export"])
    value = semantic_sidecar(manifest, meshes, socket, source_hash, glb)
    value["glbSha256"] = sha256_bytes(glb.read_bytes())
    value["payloadBytes"] = 0
    while True:
        payload = glb.stat().st_size + len(canonical_bytes(value))
        if payload == value["payloadBytes"]:
            break
        value["payloadBytes"] = payload
    write_sidecar(sidecar, value)
    run_validator(glb, sidecar, report)
    return glb, sidecar, report


def hashes(outputs, source_hash):
    return {
        "buildInputsSha256": source_hash,
        "glbSha256": sha256_bytes(outputs[0].read_bytes()),
        "sidecarSha256": sha256_bytes(outputs[1].read_bytes()),
        "validatorSha256": sha256_bytes(outputs[2].read_bytes()),
    }


def generated_typescript(manifest, actual):
    lines = [
        "// Generated by tools/art/build_slice.py. Do not edit by hand.",
        f'export const ROOM_FIXTURE_ID = "{manifest["fixtureId"]}" as const;',
        f'export const ROOM_BUILD_INPUTS_SHA256 = "{actual["buildInputsSha256"]}" as const;',
        f'export const ROOM_SIDECAR_SHA256 = "{actual["sidecarSha256"]}" as const;',
        f'export const ROOM_GLB_SHA256 = "{actual["glbSha256"]}" as const;',
        f'export const ROOM_VALIDATOR_SHA256 = "{actual["validatorSha256"]}" as const;',
        "",
    ]
    return "\n".join(lines).encode("ascii")


def main():
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("--target", choices=("room", "combatants"), default="room")
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument("--verify", action="store_true")
    modes.add_argument("--write", action="store_true")
    arguments = parser.parse_args(sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else [])
    if arguments.target == "combatants":
        from build_combatants import run
        run(arguments)
        return
    manifest = read_manifest()
    verify_blender(manifest)
    source_hash = generator_input_hash(manifest)
    with tempfile.TemporaryDirectory(prefix="room-slice-a-") as first_name, \
         tempfile.TemporaryDirectory(prefix="room-slice-b-") as second_name:
        first = build_once(Path(first_name), manifest, source_hash)
        second = build_once(Path(second_name), manifest, source_hash)
        for left, right in zip(first, second):
            if left.read_bytes() != right.read_bytes():
                if left.suffix == ".glb":
                    left_bytes, right_bytes = left.read_bytes(), right.read_bytes()
                    first_difference = next(index for index, pair in enumerate(zip(left_bytes, right_bytes)) if pair[0] != pair[1])
                    import struct
                    json_length = struct.unpack_from("<I", left_bytes, 12)[0]
                    print(f"GLB first differs at byte {first_difference}; JSON ends at {20 + json_length}; lengths {len(left_bytes)} and {len(right_bytes)}")
                    print(f"left={left_bytes[first_difference:first_difference + 24].hex()} right={right_bytes[first_difference:first_difference + 24].hex()}")
                raise RuntimeError(f"two independent exports differ: {left.name}")
        actual = hashes(first, source_hash)
        if arguments.write:
            OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
            for source in first:
                destination = OUTPUT_DIR / source.name
                temporary = destination.with_suffix(destination.suffix + ".tmp")
                shutil.copyfile(source, temporary)
                os.replace(temporary, destination)
            temporary_ts = GENERATED_TS.with_suffix(".ts.tmp")
            temporary_ts.write_bytes(generated_typescript(manifest, actual))
            os.replace(temporary_ts, GENERATED_TS)
            print(f"room slice candidate hashes: {actual}")
        else:
            expected = {
                "buildInputsSha256": source_hash,
                "glbSha256": manifest["outputs"]["glb"]["sha256"],
                "sidecarSha256": manifest["outputs"]["sidecar"]["sha256"],
                "validatorSha256": manifest["outputs"]["validator"]["sha256"],
            }
            if actual != expected:
                raise RuntimeError(f"generated hashes differ: actual={actual} expected={expected}")
            committed = (OUTPUT_DIR / "room_slice.glb", OUTPUT_DIR / "room_slice.json",
                         OUTPUT_DIR / "room_slice.validator.json")
            for generated, saved in zip(first, committed):
                if not saved.is_file() or generated.read_bytes() != saved.read_bytes():
                    raise RuntimeError(f"committed output differs: {saved}")
            if not GENERATED_TS.is_file() or GENERATED_TS.read_bytes() != generated_typescript(manifest, actual):
                raise RuntimeError(f"generated TypeScript pins differ: {GENERATED_TS}")
            print(f"room slice verified: {actual['glbSha256']}")


if __name__ == "__main__":
    main()
