// Generated by tools/art/build_slice.py --target combatants. Do not edit by hand.
export const COMBATANT_FIXTURE_ID = "v2-combatants-2" as const;
export const COMBATANT_BUILD_INPUTS_SHA256 = "5a330f273d69c88c180a5d3f4294284ace3cb507b6ddaf641ce559abc706c657" as const;
export const COMBATANT_SIDECAR_SHA256 = "315fca274cad90f423c547c63a0758696be1cb697cd026ea24737a600d06dc92" as const;
export const COMBATANT_GLB_SHA256 = "6b4e3225feb49799b0c73a057acf498342eed63461ca63509973d2cd016a84c5" as const;
export const COMBATANT_VALIDATOR_SHA256 = "41c905bb1e90a798d8e8679203f1e2b23bf4e12f747d93d256951d2f22ea096a" as const;
