// Generated by tools/art/build_slice.py --target combatants. Do not edit by hand.
export const COMBATANT_FIXTURE_ID = "v2-combatants-2" as const;
export const COMBATANT_BUILD_INPUTS_SHA256 = "094b2fad416697f404322a6559c9102a64806bd741df887935aaa66dccd52b92" as const;
export const COMBATANT_SIDECAR_SHA256 = "4dc884c004d84225d06f6369d0ca2d02ebf61f64f9c61cae03bd97ba9e5c5c3d" as const;
export const COMBATANT_GLB_SHA256 = "9e4ed670604c25dacbad013a9d387115ea5a1e5ac678f8a5b45b077cbf48e0a6" as const;
export const COMBATANT_VALIDATOR_SHA256 = "943fb943a1c2d41a71feb7a9db5f40e8dd840cab91c1c6457b0d962fec92c832" as const;
