// Generated by tools/art/build_slice.py --target combatants. Do not edit by hand.
export const COMBATANT_FIXTURE_ID = "v2-combatants-1" as const;
export const COMBATANT_BUILD_INPUTS_SHA256 = "6f0f5901e5f6264f1e8d71b8247d26099a5543ae3221d2581268377c37dd36cd" as const;
export const COMBATANT_SIDECAR_SHA256 = "891ffaee0e2c0c9a688e468a428125b27756c6eb8310a839459b47958f4a54e3" as const;
export const COMBATANT_GLB_SHA256 = "fc97d65b9a94e5b6e4d4fa71feee4a6e3cfedc4586d9f870e0d45484e460c494" as const;
export const COMBATANT_VALIDATOR_SHA256 = "30efbc643157d3a10ae71d39d0a389e6ae2996e88f09b95f771b497fe23b0eda" as const;
