// Generated by tools/art/build_slice.py. Do not edit by hand.
export const ROOM_FIXTURE_ID = "v2-room-slice-1" as const;
export const ROOM_BUILD_INPUTS_SHA256 = "31cbfe0e8244257084e5d043d0863959b3207c6f28252c8b8faeb36da4d34b9c" as const;
export const ROOM_SIDECAR_SHA256 = "1a6d972a6d27272e5126e3cc89e1891b6f97cbd1b6d9a21363cf4a58d67cf407" as const;
export const ROOM_GLB_SHA256 = "91479310571aa0b0291532e63f9549fdf79914d19dfe6c1f8b8a09fd550a6420" as const;
export const ROOM_VALIDATOR_SHA256 = "2b694efd3b4c44d33228da1a2417d186d04455752c5b09882df07c6a31ed72ff" as const;
