// Generated by tools/art/build_slice.py. Do not edit by hand.
export const ROOM_FIXTURE_ID = "v2-room-slice-1" as const;
export const ROOM_BUILD_INPUTS_SHA256 = "b63c1075e84368ec98c3ea0bb5d8767ce77494d360ae38df38456b27892dc969" as const;
export const ROOM_SIDECAR_SHA256 = "f2c4ffd8db9ffcd31b88a8824fac5b7e7dca76d15e6768d1f809d6802ea114b5" as const;
export const ROOM_GLB_SHA256 = "a680684f40ddce4164d8627b8fcee927af24f4f6c49198e95eadf12bbaf93449" as const;
export const ROOM_VALIDATOR_SHA256 = "b32b32e6792f613b3a6d8349b43df62b5c67a511d996fb7152046d190ac6a939" as const;
