// Generated by tools/art/build_slice.py. Do not edit by hand.
export const ROOM_FIXTURE_ID = "v2-room-slice-1" as const;
export const ROOM_BUILD_INPUTS_SHA256 = "a8c98a41336f25e67bc635b7251dc4a68fe93e7b3bd72a5f275fba51aee04f74" as const;
export const ROOM_SIDECAR_SHA256 = "b15c44c454a908eaabbe8c19ecc1bd13bd58fd28935a5b4bef7c9583175a0635" as const;
export const ROOM_GLB_SHA256 = "cfd30f7fc7a105e3ad6f181266fb1a2c1f6034a0866208fa71d5fd565b7fdc10" as const;
export const ROOM_VALIDATOR_SHA256 = "40a93c34e397e59da0c4372e7f68f645e8d66a2ced6e714071465d693eec90f0" as const;
