"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { test } = require("node:test");

const { audit } = require("./check_deps.js");

const INTEGRITY = `sha512-${Buffer.alloc(64).toString("base64")}`;

function write(root, rel, body) {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
}

function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "auto-rpg-deps-"));
  write(root, "Cargo.toml", '[workspace]\nresolver = "2"\nmembers = ["crates/fx", "crates/sim", "crates/policy"]\n');
  write(root, "Cargo.lock", "# This file is automatically @generated by Cargo.\nversion = 4\n");
  for (const name of ["fx", "sim", "policy"]) {
    write(root, `crates/${name}/Cargo.toml`, `[package]\nname = "${name}"\nversion = "0.1.0"\nedition = "2021"\n`);
    write(root, `crates/${name}/src/lib.rs`, "");
  }
  write(root, "tools/toolchain.json", JSON.stringify({
    node: "22.12.0",
    npm: "10.9.0",
    manifests: [
      "Cargo.toml",
      "Cargo.lock",
      "crates/fx/Cargo.toml",
      "crates/sim/Cargo.toml",
      "crates/policy/Cargo.toml",
      "tools/toolchain.json",
    ],
  }));
  return root;
}

function problems(root) {
  try {
    return audit(root);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

function npmFiles(root, manifest, packages) {
  write(root, "package.json", JSON.stringify(manifest));
  write(root, "package-lock.json", JSON.stringify({
    name: manifest.name,
    version: manifest.version,
    lockfileVersion: 3,
    requires: true,
    packages,
  }));
  const toolchainFile = path.join(root, "tools", "toolchain.json");
  const toolchain = JSON.parse(fs.readFileSync(toolchainFile, "utf8"));
  toolchain.manifests.push("package.json", "package-lock.json");
  write(root, "tools/toolchain.json", JSON.stringify(toolchain));
}

test("deterministic crates reject normal build and dev registry dependencies", () => {
  const root = fixture();
  write(root, "crates/fx/Cargo.toml", [
    '[package]', 'name = "fx"', 'version = "0.1.0"', 'edition = "2021"',
    '[dependencies]', 'normal_dep = "=1.0.0"',
    '[build-dependencies]', 'build_dep = "=1.0.0"',
    '[dev-dependencies]', 'dev_dep = "=1.0.0"', '',
  ].join("\n"));
  const errors = problems(root).join("\n");
  assert.match(errors, /fx -> normal_dep \(normal, registry\)/);
  assert.match(errors, /fx -> build_dep \(build, registry\)/);
  assert.match(errors, /fx -> dev_dep \(dev, registry\)/);
});

test("deterministic policy rejects a git dependency", () => {
  const root = fixture();
  write(root, "crates/policy/Cargo.toml", [
    '[package]', 'name = "policy"', 'version = "0.1.0"', 'edition = "2021"',
    '[dependencies]', 'remote = { git = "https://example.invalid/remote.git", rev = "0123456789abcdef0123456789abcdef01234567" }', '',
  ].join("\n"));
  assert.match(problems(root).join("\n"), /policy -> remote \(normal, git\)/);
});

test("workspace inheritance cannot hide a source", () => {
  const root = fixture();
  write(root, "Cargo.toml", [
    '[workspace]', 'resolver = "2"', 'members = ["crates/fx", "crates/sim", "crates/policy"]',
    '[workspace.dependencies]', 'hidden = "=1.0.0"', '',
  ].join("\n"));
  write(root, "crates/sim/Cargo.toml", [
    '[package]', 'name = "sim"', 'version = "0.1.0"', 'edition = "2021"',
    '[dependencies]', 'hidden = { workspace = true }', '',
  ].join("\n"));
  assert.match(problems(root).join("\n"), /sim -> hidden \(normal, registry\)/);
});

test("deterministic crates reject custom build targets", () => {
  const root = fixture();
  write(root, "crates/fx/build.rs", "fn main() {}\n");
  assert.match(
    problems(root).join("\n"),
    /deterministic dependency path fx uses forbidden custom-build target build-script-build/,
  );
});

test("deterministic workspace packages cannot escape through their own realpath", () => {
  const root = fixture();
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), "auto-rpg-outside-fx-"));
  write(outside, "Cargo.toml", '[package]\nname = "fx"\nversion = "0.1.0"\nedition = "2021"\n');
  write(outside, "src/lib.rs", "");
  const member = path.relative(root, outside).replaceAll("\\", "/");
  write(root, "Cargo.toml", [
    '[workspace]', 'resolver = "2"',
    `members = ["${member}", "crates/sim", "crates/policy"]`, '',
  ].join("\n"));
  let errors;
  try {
    errors = audit(root).join("\n");
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
    fs.rmSync(outside, { recursive: true, force: true });
  }
  assert.match(
    errors,
    /workspace package fx leaves the repository after realpath resolution|is not hierarchically below the workspace root/,
  );
});

test("npm manifest and lock must agree", () => {
  const root = fixture();
  npmFiles(root, {
    name: "fixture", version: "1.0.0", private: true,
    dependencies: { exact: "1.2.3", ranged: "^2.0.0" },
  }, {
    "": { name: "fixture", version: "1.0.0", dependencies: { exact: "1.2.4", ranged: "^2.0.0" } },
    "node_modules/exact": { version: "1.2.4", resolved: "https://registry.npmjs.org/exact/-/exact-1.2.4.tgz" },
  });
  const errors = problems(root).join("\n");
  assert.match(errors, /ranged must be an exact version/);
  assert.match(errors, /exact.*manifest requests "1\.2\.3"/);
  assert.match(errors, /node_modules\/exact resolved "1\.2\.4"/);
  assert.match(errors, /node_modules\/ranged/);
  assert.match(errors, /no valid lockfile integrity/);
});

test("every_transitive_lock_edge_resolves_through_the_npm_ancestor_chain", () => {
  const root = fixture();
  npmFiles(root, {
    name: "fixture", version: "1.0.0", private: true,
    dependencies: { parent: "1.0.0" },
  }, {
    "": { name: "fixture", version: "1.0.0", dependencies: { parent: "1.0.0" } },
    "node_modules/parent": {
      version: "1.0.0", resolved: "https://registry.npmjs.org/parent/-/parent-1.0.0.tgz",
      integrity: INTEGRITY, dependencies: { deleted: "2.0.0" },
    },
  });
  assert.match(
    problems(root).join("\n"),
    /node_modules\/parent\.dependencies\.deleted has no lock entry in its npm ancestor chain/,
  );
});

test("orphan lock records and lifecycle exceptions fail closed", () => {
  const root = fixture();
  npmFiles(root, { name: "fixture", version: "1.0.0", private: true }, {
    "": { name: "fixture", version: "1.0.0" },
    "node_modules/fsevents": {
      version: "2.3.3", resolved: "https://registry.npmjs.org/fsevents/-/fsevents-2.3.3.tgz",
      integrity: INTEGRITY, hasInstallScript: true, optional: true, os: ["darwin"],
    },
  });
  const errors = problems(root).join("\n");
  assert.match(errors, /node_modules\/fsevents is unreachable from the root manifest/);
  assert.match(errors, /reachable transitive false/);
});

test("integrity_must_decode_to_the_length_named_by_its_algorithm", () => {
  const root = fixture();
  npmFiles(root, {
    name: "fixture", version: "1.0.0", private: true,
    dependencies: { exact: "1.2.3" },
  }, {
    "": { name: "fixture", version: "1.0.0", dependencies: { exact: "1.2.3" } },
    "node_modules/exact": {
      version: "1.2.3", resolved: "https://registry.npmjs.org/exact/-/exact-1.2.3.tgz",
      integrity: "sha512-Zg==",
    },
  });
  assert.match(problems(root).join("\n"), /node_modules\/exact has no valid lockfile integrity/);
});

test("npm lifecycle scripts fail closed", () => {
  const root = fixture();
  npmFiles(root, {
    name: "fixture", version: "1.0.0", private: true,
    scripts: { test: "node --test", postinstall: "node surprise.js" },
    dependencies: { exact: "1.2.3" },
  }, {
    "": { name: "fixture", version: "1.0.0", dependencies: { exact: "1.2.3" } },
    "node_modules/exact": {
      version: "1.2.3", resolved: "https://registry.npmjs.org/exact/-/exact-1.2.3.tgz",
      integrity: INTEGRITY, hasInstallScript: true,
    },
  });
  const errors = problems(root).join("\n");
  assert.match(errors, /lifecycle script postinstall/);
  assert.match(errors, /node_modules\/exact has an unaudited lifecycle install script/);
  assert.doesNotMatch(errors, /lifecycle script test/);
});

test("the audited optional Darwin watcher is the only lifecycle exception", () => {
  const root = fixture();
  npmFiles(root, {
    name: "fixture", version: "1.0.0", private: true,
    dependencies: { watcher: "1.0.0" },
  }, {
    "": { name: "fixture", version: "1.0.0", dependencies: { watcher: "1.0.0" } },
    "node_modules/watcher": {
      version: "1.0.0", resolved: "https://registry.npmjs.org/watcher/-/watcher-1.0.0.tgz",
      integrity: INTEGRITY, dependencies: { fsevents: "2.3.3" },
    },
    "node_modules/fsevents": {
      version: "2.3.3", resolved: "https://registry.npmjs.org/fsevents/-/fsevents-2.3.3.tgz",
      integrity: INTEGRITY, hasInstallScript: true, optional: true, os: ["darwin"],
    },
  });
  assert.deepEqual(problems(root), []);
});

test("a lifecycle exception fails when any audited field drifts", () => {
  const root = fixture();
  npmFiles(root, {
    name: "fixture", version: "1.0.0", private: true,
    dependencies: { fsevents: "2.3.4" },
  }, {
    "": { name: "fixture", version: "1.0.0", dependencies: { fsevents: "2.3.4" } },
    "node_modules/fsevents": {
      version: "2.3.4", resolved: "https://registry.npmjs.org/fsevents/-/fsevents-2.3.4.tgz",
      integrity: INTEGRITY, hasInstallScript: true, optional: false, os: ["linux"],
    },
  });
  const errors = problems(root).join("\n");
  assert.match(errors, /does not match its audited exception/);
  assert.match(errors, /got version "2\.3\.4", optional false, os \["linux"\], direct true/);
});

test("unknown tool manifests fail closed", () => {
  const root = fixture();
  write(root, "tools/requirements-build.txt", "mystery-tool==1.2.3\n");
  assert.match(problems(root).join("\n"), /tools\/requirements-build\.txt: tool or asset dependency manifest is not covered/);
});

test("content asset manifests require explicit toolchain coverage", () => {
  const root = fixture();
  write(root, "web/assets/manifest.json", "{}\n");
  assert.match(
    problems(root).join("\n"),
    /web\/assets\/manifest\.json: tool or asset dependency manifest is not covered/,
  );
});
