// Regenerates the three pipeline fixtures under web/assets/.
//
//     node tools/gen_test_assets.js
//
// The fixtures are the three transforms the renderer can get wrong -- a
// `surface`, an `actor` and a `weapon` -- and they are *supposed* to look
// wrong. A magenta checkerboard that comes out as a rhombus of rhombuses is a
// projection applied twice, caught before it costs a generation batch; a
// deliberately ugly test asset is the only one whose defects are unambiguous.
// They are not art and are never regenerated by an image session.
//
// This script is committed rather than run once and thrown away, for the same
// reason `tools/gen_sin_table.js` is: a fixture nobody can rebuild is a fixture
// nobody can adjust, and the numbers below (109 x 116 in a 128 x 160 cell, 344
// square, the notch heights) are the contract `tools/measure_assets.js` checks.
// If one moves, it moves here and the tool re-measures it.
//
// PNG is written by hand on zlib.deflateSync because this repository takes no
// npm dependencies -- see the header of tools/measure_assets.js, which decodes
// them by hand for the same reason. That the two are independent
// implementations is the point: the fixtures round-trip through an encoder and
// a decoder that share no code, and then through the browser, which shares even
// less.
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");

const ASSETS = path.resolve(__dirname, "..", "web", "assets");

// ------------------------------------------------------------------- the PNG

const SIGNATURE = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

let CRC_TABLE = null;
function crc32(buf) {
  if (CRC_TABLE === null) {
    CRC_TABLE = new Int32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      CRC_TABLE[n] = c;
    }
  }
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, body) {
  const out = Buffer.alloc(body.length + 12);
  out.writeUInt32BE(body.length, 0);
  out.write(type, 4, "latin1");
  body.copy(out, 8);
  out.writeUInt32BE(crc32(out.subarray(4, 8 + body.length)), 8 + body.length);
  return out;
}

function paeth(a, b, c) {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  return pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
}

/**
 * An RGBA8 non-interlaced PNG.
 *
 * **The filter type cycles 0,1,2,3,4 down the image**, which is not how a real
 * encoder chooses -- a real one minimises the sum of absolute differences per
 * row and lands on Sub and Paeth almost every time. It is done here so that
 * every one of the thirty-four fixtures exercises every branch of the
 * reconstruction loop in `tools/measure_assets.js`. A decoder that quietly gets
 * Average wrong is a decoder that reads the next batch of real art wrong, and
 * the cheapest place to find that out is a checkerboard whose colours are known.
 */
function encodePng(w, h, rgba) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0);
  ihdr.writeUInt32BE(h, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type 6, RGBA
  ihdr[10] = 0; // deflate
  ihdr[11] = 0; // adaptive filtering
  ihdr[12] = 0; // non-interlaced

  const stride = w * 4;
  const raw = Buffer.alloc((stride + 1) * h);
  for (let y = 0; y < h; y++) {
    const ft = y % 5;
    const row = y * (stride + 1);
    raw[row] = ft;
    for (let i = 0; i < stride; i++) {
      const cur = rgba[y * stride + i];
      const a = i >= 4 ? rgba[y * stride + i - 4] : 0;
      const b = y > 0 ? rgba[(y - 1) * stride + i] : 0;
      const c = i >= 4 && y > 0 ? rgba[(y - 1) * stride + i - 4] : 0;
      let v = cur;
      if (ft === 1) v = cur - a;
      else if (ft === 2) v = cur - b;
      else if (ft === 3) v = cur - ((a + b) >> 1);
      else if (ft === 4) v = cur - paeth(a, b, c);
      raw[row + 1 + i] = v & 0xff;
    }
  }

  return Buffer.concat([
    SIGNATURE,
    chunk("IHDR", ihdr),
    chunk("IDAT", zlib.deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

// --------------------------------------------------------------- the drawing

/** A transparent RGBA canvas. Alpha is only ever 0 or 255 here: the fixtures
 *  carry no feather at all, which is inside the spec's "one pixel at most" and
 *  keeps `measure_assets`'s halo count at a clean zero over them. */
function canvas(w, h) {
  return { w, h, px: Buffer.alloc(w * h * 4) };
}

function fill(cv, x0, y0, w, h, rgba) {
  for (let y = Math.max(0, y0); y < Math.min(cv.h, y0 + h); y++) {
    for (let x = Math.max(0, x0); x < Math.min(cv.w, x0 + w); x++) {
      const o = (y * cv.w + x) * 4;
      cv.px[o] = rgba[0];
      cv.px[o + 1] = rgba[1];
      cv.px[o + 2] = rgba[2];
      cv.px[o + 3] = rgba[3];
    }
  }
}

const CLEAR = [0, 0, 0, 0];

// A 5x7 bitmap font, cut down to the eight glyphs the fixtures spell: the four
// facing letters and the four frame numbers. Anything wider than that is a font
// to maintain, and the fixtures do not need one.
const FONT = {
  E: ["#####", "#....", "#....", "####.", "#....", "#....", "#####"],
  N: ["#...#", "##..#", "#.#.#", "#.#.#", "#..##", "#...#", "#...#"],
  S: [".####", "#....", "#....", ".###.", "....#", "....#", "####."],
  W: ["#...#", "#...#", "#...#", "#.#.#", "#.#.#", "##.##", "#...#"],
  0: [".###.", "#...#", "#..##", "#.#.#", "##..#", "#...#", ".###."],
  1: ["..#..", ".##..", "..#..", "..#..", "..#..", "..#..", ".###."],
  2: [".###.", "#...#", "....#", "...#.", "..#..", ".#...", "#####"],
  3: ["#####", "...#.", "..#..", "...#.", "....#", "#...#", ".###."],
};

const GLYPH_W = 5;
const GLYPH_H = 7;

function textWidth(text, scale) {
  return text.length * GLYPH_W * scale + (text.length - 1) * scale;
}

function drawText(cv, text, x, y, scale, rgba) {
  let cx = x;
  for (const ch of text) {
    const glyph = FONT[ch];
    if (!glyph) throw new Error(`no glyph for ${ch}; add it to FONT`);
    for (let gy = 0; gy < GLYPH_H; gy++) {
      for (let gx = 0; gx < GLYPH_W; gx++) {
        if (glyph[gy][gx] === "#") fill(cv, cx + gx * scale, y + gy * scale, scale, scale, rgba);
      }
    }
    cx += (GLYPH_W + 1) * scale;
  }
}

function write(rel, cv) {
  const file = path.join(ASSETS, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, encodePng(cv.w, cv.h, cv.px));
  return file;
}

// ------------------------------------------------------------- the constants
//
// Everything below is `world units * PX_PER_WORLD_UNIT`, and the same three
// numbers appear in `tools/measure_assets.js`, which re-derives them from the
// sim rather than trusting this file.

const PX_PER_WORLD_UNIT = 86; // the default framing's scale
const UPRIGHT_EX = Math.SQRT2; // PROJ.ex, the retired Canvas page's upright projection

// Fighter, out of crates/sim/src/entity.rs (radius 0.45) and the retired
// Canvas page (BODY_H 3.0 radii). 109 x 116 in a 128 x 160 cell.
const FIGHTER_RADIUS = 0.45;
const FIGHTER_H_RADII = 3.0;
const CELL = [128, 160];
const DRAWN = [
  Math.round(2 * FIGHTER_RADIUS * UPRIGHT_EX * PX_PER_WORLD_UNIT),
  Math.round(FIGHTER_RADIUS * FIGHTER_H_RADII * PX_PER_WORLD_UNIT),
];

const FACINGS = ["s", "sw", "w", "nw", "n", "ne", "e", "se"];
const FRAMES = ["idle", "walk1", "walk2", "walk3"];

// ------------------------------------------------------------ env/floor_a.png
//
// 4 world units square at 86 px/unit, so 344. The check is half a world unit,
// which puts a 2x2 group of checks on each floor tile: fine enough to read as a
// checker and still aligned to the grid, so a seam that has drifted lands on a
// tile edge where it is obvious. 344 / 43 = 8 checks, an even count, which is
// what makes the pattern tile against itself.

function floorA() {
  const size = 4 * PX_PER_WORLD_UNIT;
  const check = size / 8;
  const cv = canvas(size, size);
  for (let j = 0; j < 8; j++) {
    for (let i = 0; i < 8; i++) {
      fill(cv, i * check, j * check, check, check, (i + j) % 2 ? [0, 0, 0, 255] : [255, 0, 255, 255]);
    }
  }
  return cv;
}

// ------------------------------------------- fighter/body_{facing}_{frame}.png
//
// A flat green rectangle at the drawn size, feet on the cell's bottom edge and
// horizontally centred. 128 - 109 = 19, an odd margin, so the figure cannot sit
// dead centre; it takes 9 px on the left and 10 on the right and the half-pixel
// of bias is inside `measure_assets`'s "within a pixel or two".
//
// The notch is cut out of the right edge at a different height per frame. It is
// a cut and not a painted bar so that a wrong frame is visible in the
// silhouette, and it is placed well inside the rectangle so that it cannot
// touch the alpha bounding box: all four frames of a facing must measure
// identically, because a frame whose centre has drifted makes the figure bob
// sideways as it walks and that is invisible in the file.

function bodyLayer(facing, frame, frameIndex) {
  const cv = canvas(CELL[0], CELL[1]);
  const x0 = Math.floor((CELL[0] - DRAWN[0]) / 2);
  const y0 = CELL[1] - DRAWN[1];
  fill(cv, x0, y0, DRAWN[0], DRAWN[1], [48, 168, 72, 255]);

  const ink = [0, 0, 0, 255];
  const scale = 6;
  const letters = facing.toUpperCase();
  drawText(cv, letters, x0 + Math.round((DRAWN[0] - textWidth(letters, scale)) / 2), y0 + 14, scale, ink);
  const digit = String(frameIndex);
  drawText(cv, digit, x0 + Math.round((DRAWN[0] - textWidth(digit, scale)) / 2), y0 + 62, scale, ink);

  const notchW = 14;
  const notchH = 12;
  fill(cv, x0 + DRAWN[0] - notchW, y0 + 6 + frameIndex * 26, notchW, notchH, CLEAR);
  return cv;
}

// ------------------------------------------------------- weapons/test_bar.png
//
// Drawn along +x, hilt at the left edge and tip at the right, tight-cropped to
// content. Length is free -- the renderer stretches the image between the
// projected hilt and the projected tip -- so 192 x 40 is chosen only to be big
// enough to read.
//
// **The asymmetry is the whole point.** Three notches out of the top edge at
// irregular spacing and one out of the bottom, none of it symmetric under a
// mirror or under a half turn. A bar that comes out reversed at four facings
// and correct at the other four is a sign error in the span, and against a
// symmetric bar it looks exactly like a correct one.

function testBar() {
  const cv = canvas(192, 40);
  const cyan = [0, 224, 224, 255];
  fill(cv, 0, 8, 16, 24, [255, 0, 0, 255]); // hilt marker
  fill(cv, 16, 0, 8, 40, cyan); // guard, and what makes the crop tight vertically
  fill(cv, 24, 12, 144, 16, cyan); // blade
  fill(cv, 168, 14, 24, 12, [255, 232, 0, 255]); // tip marker

  fill(cv, 40, 12, 12, 6, CLEAR);
  fill(cv, 60, 12, 6, 4, CLEAR);
  fill(cv, 96, 12, 8, 8, CLEAR);
  fill(cv, 132, 22, 12, 6, CLEAR);
  return cv;
}

// -------------------------------------------------------------------- the run

const written = [];
written.push(write("env/floor_a.png", floorA()));
written.push(write("weapons/test_bar.png", testBar()));
for (const facing of FACINGS) {
  FRAMES.forEach((frame, i) => {
    written.push(write(`fighter/body_${facing}_${frame}.png`, bodyLayer(facing, frame, i)));
  });
}

console.log(`wrote ${written.length} fixtures to ${ASSETS}`);
console.log(`  env/floor_a.png                  ${4 * PX_PER_WORLD_UNIT} square, surface`);
console.log(`  fighter/body_{facing}_{frame}.png ${CELL[0]} x ${CELL[1]} cell, ${DRAWN[0]} x ${DRAWN[1]} drawn, actor`);
console.log(`  weapons/test_bar.png             192 x 40, weapon`);
console.log("now check them: node tools/measure_assets.js");
